"""Add accuracy columns to Throw model

Revision ID: 25cf86f05268
Revises: 5123d36542a0
Create Date: 2023-04-02 20:50:38.880265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cf86f05268'
down_revision = '5123d36542a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('throw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy_x', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('accuracy_y', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('throw', schema=None) as batch_op:
        batch_op.drop_column('accuracy_y')
        batch_op.drop_column('accuracy_x')

    # ### end Alembic commands ###
